version: "3.8"
services:
  db:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/social-bookmarking-data
      POSTGRES_DB: social-bookmarking
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/social-bookmarking-data
volumes:
  db-data:
